=== SAMIMES/divers/XSD_Schemas/examples/products.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

    <xsd:element name="products" type="productsType" />

    <xsd:complexType name="productsType">
        <xsd:sequence>
            <xsd:element ref="product" maxOccurs="unbounded"/>
            <xsd:element ref="productRest"/>
            <xsd:element ref="productExt" />
        </xsd:sequence>
        <xsd:attribute name="type" type="xsd:string"/>
    </xsd:complexType>

    <xsd:element name="product" type="productType" />
    <xsd:complexType name="productType">
        <xsd:sequence>
            <xsd:element name="name" type="xsd:string"  />
            <xsd:element name="size" type="xsd:integer" />
            <xsd:element name="color" type="xsd:string" minOccurs="0" />
        </xsd:sequence>
        <xsd:attribute name="id" type="xsd:integer" />
    </xsd:complexType>

    <xsd:element name="productRest" type="productRestType" />
    <xsd:complexType name="productRestType">
        <xsd:complexContent>
            <!-- We cannot let restriction block empty, contrary to extensions -->
            <xsd:restriction base="productType">
                <xsd:sequence>
                    <xsd:element name="name" type="xsd:string"  />
                    <xsd:element name="size" type="xsd:integer" />
                </xsd:sequence>
            </xsd:restriction>
        </xsd:complexContent>
    </xsd:complexType>

    <xsd:element name="productExt" type="productExtType" />
    <xsd:complexType name="productExtType">
        <xsd:complexContent>
            <!-- If we let this block empty, it will inherit only of productType  -->
            <xsd:extension base="productType">
                <!-- choice -> C'est l'un ou l'autre mais pas les deux -->
                <xsd:choice>
                    <xsd:element name="Supplier" type="xsd:string"/>
                    <xsd:element name="Client" type="xsd:string"/>
                </xsd:choice>
            </xsd:extension>
        </xsd:complexContent>
    </xsd:complexType>









</xsd:schema>

=== SAMIMES/divers/XSD_Schemas/examples/products.xml
<?xml version="1.0" encoding="UTF-8" ?>
<products type="electronics" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="products.xsd">
    <product id="1">
        <name>Computer</name>
        <size>2</size>
        <color>Black</color>
    </product>
    <product id="2">
       <name>Smartphone</name>
        <size>2</size>
        <color>Red</color>
    </product>
    <product id="3">
        <name>Watch</name>
        <size>2</size>
        <color>Red</color>
    </product>
    <productRest>
        <name>Fridge</name>
        <size>2</size>
    </productRest>
    <productExt id="3">
        <name>Watch</name>
        <size>2</size>
        <color>Red</color>
        <!-- <Client>Sami</Client> -->
        <Supplier>Sami</Supplier>
    </productExt>

</products>

<!-- xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="products.xsd" -->
